ORG 0000H
ORL P0,#0X03;SET THE PORT PINS 

MAIN:JNB P0.0,NX_SW;CHECK THE STATUS OF 1ST SWITCH 
CLR P0.2
SJMP MAIN
NX_SW:JNB P0.1,ON;CHECK THE STATUS OF 2ST SWITCH
CLR P0.2
SJMP MAIN 
ON:SETB P0.2;ON THE LED 
SJMP MAIN 

END 

