ORG 0000H
ORL P0,#0X03;SET THE PORT PINS 
MAIN:JB P0.0,ON;CHECK THE STATUS OF 1ST SWITCH 
CLR P0.2
JB P0.1,ON;CHECK THE STATUS OF 2ST SWITCH
CLR P0.2
SJMP MAIN 
ON:SETB P0.2;CHANGE THE POSITION OF LED 
SJMP MAIN 
END 

